package org.ihtsdo.termserver.scripting.pipeline;

public interface ContentPipeLineConstants {

	enum ProcessingFlag {
		ALLOW_SPECIMEN, DROP_OUT, ALLOW_TECHNIQUE,
		MARK_AS_PRIMITIVE, ALLOW_BLANK_DIVISOR, EXPECT_BLANK_COMPONENT,
		ALTERNATIVE_COMPONENT_SUPPLIED,
		SUPPRESS_METHOD_TERM, SUPPRESS_DIVISOR_TERM,
		SPLIT_TO_GROUP_PER_COMPONENT, ALLOW_UNMODELLED_COMPONENT,
		SUPPRESS_CHARACTERIZES_TERM, ALLOW_SPECIMEN_EXCEPT_CHARACTERIZES
	}

	int GROUP_1 = 1;

	String TAB_SUMMARY = "Summary";
	String TAB_LOINC_DETAIL_MAP_NOTES = "LOINC Detail Map Notes";
	String TAB_MODELING_ISSUES = "Modeling Issues";
	String TAB_PROPOSED_MODEL_COMPARISON = "Proposed Model Comparison";
	String TAB_MAP_ME = "Map Me!";
	String TAB_IMPORT_STATUS = "Import Status";
	String TAB_STATS = "Property Stats";

	String NAME = "NAME";
}
